Repository aztfmod/terraform-provider-azurecaf, pull requests merged in 2021-02, with the labels that each got.

#81 Feb cleanup
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  README.md
  azurecaf/models_generated.go
  azurecaf/provider.go
  azurecaf/provider_test.go
  azurecaf/resource_name.go
  azurecaf/resource_name_test.go
  azurecaf/resource_naming_convention.go
  azurecaf/resource_naming_convention_cafclassic_test.go
  azurecaf/resource_naming_convention_cafrandom_test.go
  azurecaf/resource_naming_convention_passthrough_test.go
  azurecaf/resource_naming_convention_random_test.go
  azurecaf/resource_naming_convention_test.go
  go.mod
  main.go
  resourceDefinition.json
Labels: bug, enhancement

#84 add IP Group
  README.md
  azurecaf/models_generated.go
  resourceDefinition.json
Labels: enhancement

#85 Ip_group add models_generated.go
  azurecaf/models_generated.go
Labels: bug
