Repository aztfmod/terraform-provider-azurecaf, pull requests merged in 2023-03, with the labels that each got.

#229 Fix documentation
  README.md
  docs/data-sources/azurecaf_name.md
Labels: documentation

#223 Revert windows VM name length to 15 chars
  azurecaf/models_generated.go
  docs/resources/azurecaf_name.md
  resourceDefinition.json
Labels: bug

#228 Add support for Azure Container App
  README.md
  azurecaf/models.go
  azurecaf/models_generated.go
  azurecaf/resource_name_test.go
  completness/existing_tf_resources.txt
  docs/index.md
  docs/resources/azurecaf_name.md
  docs/resources/azurecaf_naming_convention.md
  resourceDefinition.json
Labels: enhancement

#231 Update workflows
  .github/workflows/go.yml
  go.mod
Labels: dependencies
